// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgaKICC9dHugiRlpKMHMTn5dgItdmVobU',
    appId: '1:111711060258:web:7d7d7ae4b982eeab8b257b',
    messagingSenderId: '111711060258',
    projectId: 'madproject-e1384',
    authDomain: 'madproject-e1384.firebaseapp.com',
    storageBucket: 'madproject-e1384.appspot.com',
    measurementId: 'G-9CHXP50RXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-FhPViz2hzMUVg14FrdZOi4zxJ1692g',
    appId: '1:111711060258:android:b1b074e8a8b9ff958b257b',
    messagingSenderId: '111711060258',
    projectId: 'madproject-e1384',
    storageBucket: 'madproject-e1384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnqhsth6WLd2yUuHxag3atA2VX1mpPxA',
    appId: '1:111711060258:ios:0fb21a1f47b34a618b257b',
    messagingSenderId: '111711060258',
    projectId: 'madproject-e1384',
    storageBucket: 'madproject-e1384.appspot.com',
    androidClientId: '111711060258-f4uscqnuapnonkmfcmlajvdpfmf1ghk5.apps.googleusercontent.com',
    iosClientId: '111711060258-lmgki4nqqblsnn7pptaqcnuvf7vpnt3r.apps.googleusercontent.com',
    iosBundleId: 'com.testing.rhb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnqhsth6WLd2yUuHxag3atA2VX1mpPxA',
    appId: '1:111711060258:ios:53dc212f449c0db08b257b',
    messagingSenderId: '111711060258',
    projectId: 'madproject-e1384',
    storageBucket: 'madproject-e1384.appspot.com',
    androidClientId: '111711060258-f4uscqnuapnonkmfcmlajvdpfmf1ghk5.apps.googleusercontent.com',
    iosClientId: '111711060258-dijnl1c7fk2f0nseanf8e5l8ipileph6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rhb',
  );
}
